In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np

df_manzanas = gpd.read_file('predata/manzanas_medellin.geojson')

df_copy = df_manzanas.copy()

df_copy = df_copy.to_crs(epsg=32618)

df_copy['area'] = df_copy.geometry.area
df_manzanas['area'] = df_copy['area']

df_barrios = gpd.read_file('predata/barrios.geojson')
df_barrios = df_barrios.to_crs(epsg=4326)
df_manzanas = df_manzanas.to_crs(epsg=4326)

df_usos = gpd.read_file('predata/usos.geojson')
joined = gpd.sjoin(df_manzanas, df_barrios, how="inner", op="intersects")
joined

C:\Users\camilo\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py:3517: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

,COD_DPTO,COD_MPIO,COD_CLASE,COD_CPOB,COD_SECC,COD_DANE,COD_AG,TIPO_CTSTR,COD_CTSTR,ANO_VGNC,...,index_right,OBJECTID,CODIGO,NOMBRE,IDENTIFICACION,LIMITECOMUNACORREGIMIENTOID,LIMITEMUNICIPIOID,SUBTIPO_BARRIOVEREDA,Shape_Length,Shape_Area
0,05,05001,1,05001000,05001100000000010101,0500110000000001010101,000001,5,050010101105,2021,...,150,151,0101,Santo Domingo Savio No.1,0101,01,001,1,3596.697702,5.612470e+05
1,05,05001,1,05001000,05001100000000010101,0500110000000001010104,000002,5,050010101064,2021,...,150,151,0101,Santo Domingo Savio No.1,0101,01,001,1,3596.697702,5.612470e+05
2,05,05001,1,05001000,05001100000000010101,0500110000000001010105,000003,5,050010101063,2021,...,150,151,0101,Santo Domingo Savio No.1,0101,01,001,1,3596.697702,5.612470e+05
3,05,05001,1,05001000,05001100000000010101,0500110000000001010108,000004,5,050010101061,2021,...,150,151,0101,Santo Domingo Savio No.1,0101,01,001,1,3596.697702,5.612470e+05
4,05,05001,1,05001000,05001100000000010101,0500110000000001010109,000005,5,0500100101100,2021,...,150,151,0101,Santo Domingo Savio No.1,0101,01,001,1,3596.697702,5.612470e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14672,05,05001,2,05001057,05001200303057000101,0500120030305700010106,012612,0,0000000000000,2021,...,155,156,9002,Media Luna,9002,90,001,2,17115.677344,9.444551e+06
14673,05,05001,2,05001066,05001200120066000101,0500120012006600010101,014085,5,0000000000000,2021,...,206,207,8007,La Verde,8007,80,001,2,13128.301027,6.694644e+06
14674,05,05001,2,05001066,05001200120066000101,0500120012006600010102,014083,5,0000000000000,2021,...,206,207,8007,La Verde,8007,80,001,2,13128.301027,6.694644e+06
14675,05,05001,2,05001066,05001200120066000101,0500120012006600010103,014086,5,0000000000000,2021,...,206,207,8007,La Verde,8007,80,001,2,13128.301027,6.694644e+06
14676,05,05001,2,05001066,05001200120066000101,0500120012006600010104,014084,5,0000000000000,2021,...,206,207,8007,La Verde,8007,80,001,2,13128.301027,6.694644e+06

In [2]:
joined.reset_index(drop=True, inplace=True)
joined.drop(columns=['index_right'], inplace=True)

In [3]:
df_final = joined

In [4]:
df_usos = df_usos.to_crs(epsg=4326)

In [5]:
df_final = gpd.sjoin(df_final, df_usos, how="inner", op="intersects")

C:\Users\camilo\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py:3517: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

In [7]:
df_final=df_final[df_final['SUBCATEGORIA'] == 'Áreas predominantemente residenciales']
df_final.drop(columns=['index_right'], inplace=True)

In [8]:
df_final

,COD_DPTO,COD_MPIO,COD_CLASE,COD_CPOB,COD_SECC,COD_DANE,COD_AG,TIPO_CTSTR,COD_CTSTR,ANO_VGNC,...,SUBTIPO_BARRIOVEREDA,Shape_Length_left,Shape_Area_left,OBJECTID_right,COD_CAT_USO,COD_SUBCAT_USO,AREAGRALUSO,SUBCATEGORIA,Shape_Length_right,Shape_Area_right
0,05,05001,1,05001000,05001100000000010101,0500110000000001010101,000001,5,050010101105,2021,...,1,3596.697702,5.612470e+05,10025,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,96.451510,434.875823
0,05,05001,1,05001000,05001100000000010101,0500110000000001010101,000001,5,050010101105,2021,...,1,3596.697702,5.612470e+05,10097,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,211.736561,973.306707
2,05,05001,1,05001000,05001100000000010101,0500110000000001010105,000003,5,050010101063,2021,...,1,3596.697702,5.612470e+05,9644,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,95.629566,371.442845
2,05,05001,1,05001000,05001100000000010101,0500110000000001010105,000003,5,050010101063,2021,...,1,3596.697702,5.612470e+05,9747,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,186.590393,1379.738225
3,05,05001,1,05001000,05001100000000010101,0500110000000001010108,000004,5,050010101061,2021,...,1,3596.697702,5.612470e+05,9856,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,213.940338,1917.577041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15898,05,05001,1,05001000,05001100000000907204,0500110000000090720422,020733,5,0000000000000,2021,...,2,7248.607098,2.040760e+06,1175,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,1204.985759,25984.020089
15899,05,05001,1,05001000,05001100000000907204,0500110000000090720423,013934,5,0000000000000,2021,...,2,7248.607098,2.040760e+06,1175,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,1204.985759,25984.020089
15901,05,05001,1,05001000,05001100000000907204,0500110000000090720425,013900,5,0000000000000,2021,...,2,7248.607098,2.040760e+06,1175,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,1204.985759,25984.020089
16032,05,05001,2,05001013,05001200216013000101,0500120021601300010111,020906,5,0000000000000,2021,...,1,4476.377677,4.621203e+05,733,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,436.120097,7245.570611
16033,05,05001,2,05001013,05001200216013000101,0500120021601300010111,020906,5,0000000000000,2021,...,2,11999.385360,2.072611e+06,733,1,11,Áreas de baja mixtura,Áreas predominantemente residenciales,436.120097,7245.570611

In [9]:
df_estratos = gpd.read_file('predata/estrato.geojson')
df_estratos = df_estratos.dropna(subset=['MANZANA'])
df_estratos.reset_index(drop=True, inplace=True)
df_estratos = df_estratos.to_crs(epsg=4326)
df_promedio_estrato = df_estratos.groupby('MANZANA')['ESTRATO'].mean().reset_index()

df_promedio_estrato['ESTRATO_PROMEDIO'] = np.floor(df_promedio_estrato['ESTRATO'])

df_estratos = df_estratos.merge(df_promedio_estrato[['MANZANA', 'ESTRATO_PROMEDIO']], on='MANZANA', how='left')

df_estratos = df_estratos.drop_duplicates(subset='MANZANA')

df_estratos.drop(columns=['ESTRATO'], inplace=True)

df_estratos.rename(columns={'ESTRATO_PROMEDIO': 'ESTRATO'}, inplace=True)

In [10]:
df_estratos.reset_index(drop=True, inplace=True)

In [12]:
df_final1 = gpd.sjoin(df_final, df_estratos, how="left", op="intersects")

C:\Users\camilo\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py:3517: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

In [14]:
cols=["geometry", "area", "MANZANA", "NOMBRE", "BARRIO", "ESTRATO"]
df_final1=df_final1[cols]

In [15]:
df_final1=df_final1.dropna()
df_final1 = df_final1.drop_duplicates(subset='geometry')

In [16]:
df_final1.reset_index(drop=True, inplace=True)
df_final=df_final1

In [17]:
df_poblacion_barrios = pd.read_csv('predata/poblacion-barrios.csv')

df_area_barrio = df_final.groupby('NOMBRE')['area'].sum().reset_index()
df_area_barrio.columns = ['NOMBRE', 'AREA_TOTAL_BARRIO']

df_final = pd.merge(df_final, df_area_barrio, on='NOMBRE', how='left')
df_final = pd.merge(df_final, df_poblacion_barrios, on='NOMBRE', how='left')
df_final['POBLACION_MANZANA'] = df_final['POBLACION'] * df_final['area']/df_final['AREA_TOTAL_BARRIO']

df_final['POBLACION_MANZANA'].fillna(0, inplace=True)
df_final['POBLACION_MANZANA'] = np.ceil(df_final['POBLACION_MANZANA'])
df_final

C:\Users\camilo\AppData\Local\Temp\ipykernel_5132\2281534757.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['POBLACION_MANZANA'].fillna(0, inplace=True)

,geometry,area,MANZANA,NOMBRE,BARRIO,ESTRATO,AREA_TOTAL_BARRIO,POBLACION,POBLACION_MANZANA
0,"POLYGON ((-75.54280 6.29964, -75.54277 6.29959...",2556.770524,0101063,Santo Domingo Savio No.1,01,2.0,282046.627796,5238.0,48.0
1,"POLYGON ((-75.54386 6.29974, -75.54386 6.29975...",1923.572850,0101061,Santo Domingo Savio No.1,01,1.0,282046.627796,5238.0,36.0
2,"POLYGON ((-75.54369 6.30214, -75.54369 6.30213...",1046.679014,0101059,Santo Domingo Savio No.1,01,1.0,282046.627796,5238.0,20.0
3,"POLYGON ((-75.54536 6.30129, -75.54533 6.30128...",2297.898023,0101057,Santo Domingo Savio No.1,01,1.0,282046.627796,5238.0,43.0
4,"POLYGON ((-75.54377 6.30277, -75.54376 6.30273...",1952.989673,0101060,Santo Domingo Savio No.1,01,1.0,282046.627796,5238.0,37.0
...,...,...,...,...,...,...,...,...,...
7926,"POLYGON ((-75.62280 6.22204, -75.62282 6.22201...",1642.052921,7083004,La Esperanza,83,2.0,361824.566849,3729.0,17.0
7927,"POLYGON ((-75.62264 6.22228, -75.62264 6.22228...",4242.611254,7083002,La Esperanza,83,2.0,361824.566849,3729.0,44.0
7928,"POLYGON ((-75.62258 6.22197, -75.62257 6.22200...",1357.352659,7083003,La Esperanza,83,2.0,361824.566849,3729.0,14.0
7929,"POLYGON ((-75.62280 6.22198, -75.62274 6.22196...",1576.995018,7083003,La Esperanza,83,2.0,361824.566849,3729.0,17.0
7930,"POLYGON ((-75.62240 6.22145, -75.62232 6.22139...",381.112347,7083002,La Esperanza,83,2.0,361824.566849,3729.0,4.0

In [18]:
df_final.to_file("data.geojson", driver='GeoJSON')

In [167]:
import folium
mapa = folium.Map(location=[df_final.geometry.centroid.y.mean(), df_final.geometry.centroid.x.mean()], zoom_start=13)

for idx, row in df_final.iterrows():
    area_formateada = "{:.2f}".format(row['area'])
    etiqueta = f"Barrio: {row['NOMBRE']}, Área: {area_formateada} m², Población: {row['POBLACION_MANZANA']}, estrato: {row['ESTRATO']}"
    folium.GeoJson(row.geometry, tooltip=etiqueta).add_to(mapa)

mapa.save('mapa.html')

C:\Users\camilo\AppData\Local\Temp\ipykernel_18188\3139884313.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  mapa = folium.Map(location=[df_final.geometry.centroid.y.mean(), df_final.geometry.centroid.x.mean()], zoom_start=13)

In [ ]:
import folium
mapa = folium.Map(location=[df_final.geometry.centroid.y.mean(), df_final.geometry.centroid.x.mean()], zoom_start=13)

for idx, row in df_final.iterrows():
    etiqueta = f"Coleigo: {row['COLE_INST_NOMBRE']}"
    folium.GeoJson(row.geometry, tooltip=etiqueta).add_to(mapa)

mapa.save('mapa_reales.html')